---
title: "hy2580_dept"
author: "haokun yuan"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Untitled"
author: "haokun yuan"
date: "5/14/2019"
output: html_document
---

```{r setup, include=FALSE}
library(caret)
library(splines)
library(mgcv)
library(tidyverse)
library(ggplot2)
library(glmnet)
library(pls)
library(randomForest)
library(MASS)
```

Data Cleaning
```{r}
df = read_csv("data/merged_data_2.csv") %>%
  janitor::clean_names() %>% 
  filter(dept == 3) %>% 
  dplyr::select(is_holiday,weekly_sales,cpi,unemployment,size,type,temperature, fuel_price)

df$is_holiday=as.factor(df$is_holiday)
df$type = as.factor((df$type))
```

test and train
```{r}
# seperate test and train 
smp_size <- floor(0.75 * nrow(df))
set.seed(123)
train_ind <- sample(seq_len(nrow(df)), size = smp_size)

train.data <- df[train_ind, ]
test.data  <- df[-train_ind, ]

x <- model.matrix(weekly_sales~.,train.data)[,-1]
y <- train.data$weekly_sales

newx =  model.matrix(weekly_sales~.,test.data)[,-1]
newy =  test.data$weekly_sales

```
caret control
```{r}
ctrl1 <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
```
LM
```{r}
#linear 
set.seed(2)
lm.fit <- train(weekly_sales~.,
                data= train.data,
                method = "lm",
                trControl = ctrl1)
```
Ridge
```{r}
#ridge
set.seed(2)
ridge.fit <- train(weekly_sales~.,
                   data= train.data,
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 0, 
                                          lambda = exp(seq(6.246, 6.255, length=100))),
                   # preProc = c("center", "scale"),
                   trControl = ctrl1)

plot(ridge.fit, xTrans = function(x) log(x))
```

LASSO
```{r}
set.seed(2)
lasso.fit <- train(weekly_sales~.,
                   data= train.data,
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 1, 
                                          lambda = exp(seq(2, 3, length=100))),
                   # preProc = c("center", "scale"),
                   trControl = ctrl1)
plot(lasso.fit, xTrans = function(x) log(x))
```

PCR
```{r}
set.seed(2)
pcr.fit <- train(weekly_sales~.,
                 data= train.data,
                 method = "pcr",
                 tuneLength = 7,
                 trControl = ctrl1,
                 preProc = c("center", "scale") )
# # need to preprocess your data when using predict()
trans <- preProcess(x, method = c("center", "scale"))
predy2.pcr2 <- predict(pcr.fit$finalModel, 
                       newdata = predict(trans,test.data),
                       ncomp = pcr.fit$bestTune[[1]])
ggplot(pcr.fit, highlight = TRUE)+ theme_bw()
```

PLS
```{r}
set.seed(2)
pls.fit <-train(x, y,
                method = "pls",
                tuneLength = 18,
                trControl = ctrl1,
                scale = TRUE)

predy2.pls2 <-predict(pls.fit$finalModel,
                      newdata = test.data,
                      ncomp = pls.fit$bestTune$ncomp)
ggplot(pls.fit, highlight = TRUE)
```

GAM
```{r}
# GAM
gam.m1 <- gam(weekly_sales ~store+is_holiday+temperature+
                fuel_price+cpi+unemployment+type+size+
                week_of_year+year+month_of_year+dept,
              data = train.data)

gam.m2 <- gam(weekly_sales~store+is_holiday+
                s(temperature)+fuel_price+cpi+
                unemployment+type+size+week_of_year+
                year+month_of_year+dept,
              data = train.data)

gam.m3 <- gam(weekly_sales ~store+is_holiday+
                s(temperature)+s(fuel_price)+cpi+
                unemployment+type+size+week_of_year+
                year+month_of_year+dept,
              data = train.data)

gam.m4 <- gam(weekly_sales ~store+is_holiday+
                s(temperature)+s(fuel_price)+s(cpi)+
                s(unemployment)+type+size+week_of_year+
                year+month_of_year+dept,
              data = train.data)

gam.m5 <- gam(weekly_sales ~store+is_holiday+
                s(temperature)+s(fuel_price)+s(cpi)+
                s(unemployment)+type+s(size)+
                week_of_year+year+month_of_year+dept,
              data = train.data)

gam.m6 <- gam(weekly_sales ~ store+is_holiday+
                s(temperature)+s(fuel_price)+s(cpi)+
                s(unemployment)+type+s(size)+
                s(week_of_year)+year+s(month_of_year)+
                dept, 
              data = train.data)

gam.m7 <- gam(weekly_sales ~store+is_holiday+
                s(temperature)+s(fuel_price)+s(cpi)+
                s(unemployment)+type+s(size)+
                te(week_of_year,month_of_year)+year+
                dept,
              data = train.data)

gam.m8 <- gam(weekly_sales ~store+is_holiday+s(cpi)+
                s(unemployment)+type+s(size)+
                te(week_of_year,month_of_year,                                   temperature,fuel_price)+
                year+dept,
              data = train.data)

anova(gam.m1, gam.m2, gam.m3, gam.m4,
      gam.m5, gam.m6, gam.m8, gam.m7, test = "F")
AIC(gam.m1, gam.m2, gam.m3, gam.m4, gam.m5, gam.m6,
    gam.m7, gam.m8)

plot(gam.m3)
```

```{r}
ctrl <- trainControl(method = "cv")
set.seed(1)
bg.fit <- train(weekly_sales ~ ., 
                df,
                method = "ranger",
                tuneGrid = expand.grid(
                          mtry = 83, 
                          splitrule = "variance",
                          min.node.size = 10 ),
                importance = "permutation",
                scale.permutation.importance = "TRUE",
                trControl = ctrl1)

# plot variable of importance 
barplot(sort(ranger::importance(bg.fit$finalModel), decreasing = FALSE),
        las = 2, horiz = TRUE, cex.names = 0.7)
```

```{r}
rf.grid <- expand.grid(mtry = seq(4,134,10),
                       splitrule = "variance",
                       min.node.size = 10)
set.seed(1)
rf.fit <- train(weekly_sales~., df,
                method = "ranger",
                tuneGrid = rf.grid,
                trControl = ctrl)

#rf.fit$bestTune
ggplot(rf.fit, highlight = TRUE)
```


Model Selection
```{r}
resamp <- resamples(list(lasso = lasso.fit, 
                         ridge = ridge.fit, 
                         lm = lm.fit,
                         pcr = pcr.fit,
                         pls = pls.fit))

bwplot(resamp, metric = "RMSE")
```

