---
title: "Sc456"
author: "Siyan Chen"
date: "4/5/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(corrplot)
library(caret)
library(glmnet)
```


### import data 

```{r}
raw_df_train = read_csv("data/train.csv")
raw_df_stores = read_csv("data/stores.csv")
raw_df_ftrs = read_csv("data/features.csv")
raw_df_test = read_csv("data/test.csv")
df_merged = merge(merge(raw_df_train,raw_df_ftrs),raw_df_stores)

library(lubridate)

df_merged$week_of_year = week(df_merged$Date)

  
```

```{r}
unique(raw_df_train$Date) == unique(df_merged$Date)
all.equal(unique(raw_df_train$IsHoliday) ,unique(df_merged$IsHoliday))
all.equal(unique(raw_df_train$Date) ,unique(df_merged$Date))
#colnames(raw_df_ftrs)[c(2,12)] = c("ftr_Date" ,"ftr_IsHoliday")
# merge_1 = merge(raw_df_train,raw_df_ftrs)
# merge_2 = merge(merge_1,raw_df_stores)

```

### we cannot change to 0 and 1-------

```{r}
## change markdown to either have or don't have markdown 
#df_merged$MarkDown1 = ifelse(is.na(df_merged$MarkDown1),0,1)
#df_merged$MarkDown2 = ifelse(is.na(df_merged$MarkDown2),0,1)
#df_merged$MarkDown3 = ifelse(is.na(df_merged$MarkDown3),0,1)
#df_merged$MarkDown4 = ifelse(is.na(df_merged$MarkDown4),0,1)
#df_merged$MarkDown5 = ifelse(is.na(df_merged$MarkDown5),0,1)
table(df_merged$MarkDown1)
```

# CLEAN DATA

```{r}
# 2011 before December: no markdown, NA change to 0, other NA kept
df_cleaned1 = df_merged %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "date"), sep = "-") %>% 
  gather(key = holiday_markdown, value = markdown_amount, mark_down1:mark_down5)

df_cleaned2 = df_merged %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "date"), sep = "-") %>% 
  gather(key = holiday_markdown, value = markdown_amount, mark_down1:mark_down5)%>% 
  filter(year == 2011 & month < 12)

df_cleaned2$markdown_amount=ifelse(is.na(df_cleaned2$markdown_amount),0,1)

df_cleaned3 = anti_join(df_cleaned1, df_cleaned2)
df_cleaned = rbind(df_cleaned2,df_cleaned3)
  

  
table(df_cleaned$year)
table(df_cleaned$month)

summary(is.na(df_cleaned)) ### only markdown variable have NA
summary(is.na(df_cleaned$markdown_amount))

df1 = na.omit(df_cleaned) %>% 
  mutate(dept = as.factor(dept))
df = sample_frac(df1, 0.01, replace = TRUE)

```


```{r}
x = model.matrix(weekly_sales~., df)[,-1]
y = df$weekly_sales
corrplot(cor(x))
```


# ridge

```{r}
ctrl1 = trainControl(method = "repeatedcv", number = 10, repeats = 5)
set.seed(2)
ridge.fit = train(x,y,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 0,
                                         lambda = exp(seq(-1,10, length = 100))),
                  trControl = ctrl1)
plot(ridge.fit, xTrans = function(x)log(x))
ridge.fit$bestTune
coef(ridge.fit$finalModel, ridge.fit$bestTune$lambda)
```

#lasso

```{r}
set.seed(2)
lasso.fit = train(x, y,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 1,
                                         lambda = exp(seq(-1,10, length = 100))),
                  trControl = ctrl1)
plot(lasso.fit, xTrans = function(x)log(x))
coef(lasso.fit$finalModel, ridge.fit$bestTune$lambda)

```

test_performance

```{r}
resamp = resamples(list(lass = lasso.fit, ridge = ridge.fit))
summary(resamp)
```

